# -*- coding: utf-8 -*-
"""AI_2402

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zIUoWu8SGACoc06_k_Gwzcp8DFfMVFyl
"""

pip skfuzzy

pip skfuzzy

pip skfuzzy

pip install scikit-fuzzy



import numpy as np 
import skfuzzy as fuzz 
import matplotlib.pyplot as plt 
x = np.arange(30,81,1)

slow = fuzz.trimf(x,[30,30,50])

mediumfast = fuzz.trimf(x,[40,60,80])

fullspeed  = fuzz.trimf(x,[50,70,80])

plt.figure()

plt.plot(x,slow,'r',linewidth=1.5, label = ' slow')

plt.plot(x,mediumfast,'r',linewidth=1.5, label = ' slow')

plt.plot(x,fullspeed,'r',linewidth=1.5, label = ' slow')

plt.plot(x,mediumfast,'r',linewidth=1.5, label = ' slow')

plt.plot(x,slow,'r',linewidth=1.5, label = ' slow')
plt.plot(x,mediumfast,'r',linewidth=1.5, label = ' slow')
plt.plot(x,fullspeed,'r',linewidth=1.5, label = ' slow')

slow = fuzz.trapmf(x,[30,30,30,50])
mediumfast =  fuzz.trapmf(x,[40,60,60,80])
fullspeed  = fuzz.trapmf(x,[50,70,70,80])

plt.plot(x,slow,'r',linewidth=1.5, label = ' slow')
plt.plot(x,mediumfast,'blue',linewidth=1.5, label = ' slow')
plt.plot(x,fullspeed,'black',linewidth=1.5, label = ' slow')

slow = fuzz.gaussmf(x,30,5)
mediumfast = fuzz.gaussmf(x,40,5)
fullspeed = fuzz.gaussmf(x,50,5)
action = fuzz.gaussmf(x,60,5)

plt.plot(x,slow,'r',linewidth=1.5, label = ' slow')
plt.plot(x,mediumfast,'blue',linewidth=1.5, label = ' slow')
plt.plot(x,fullspeed,'black',linewidth=1.5, label = ' slow')

plt.plot(x,slow,'r',linewidth=1.5, label = ' slow')
plt.plot(x,mediumfast,'blue',linewidth=1.5, label = ' slow')
plt.plot(x,fullspeed,'black',linewidth=1.5, label = ' slow')
plt.plot(x,action,'green',linewidth=1.5, label = ' slow')

slow = fuzz.trapmf(x,[0,5,5,10])
mediumfast =  fuzz.trapmf(x,[,60,60,80])
fullspeed  = fuzz.trapmf(x,[50,70,70,80])

"""TIP IN RESTAURANT """

import numpy as np 
import skfuzzy as fuzz 
import matplotlib.pyplot as plt 
from skfuzzy import control as ctrl

food = ctrl.Antecedent(np.arange(0,11,1),'food')
service = ctrl.Antecedent(np.arange(0,11,1),'service')
tip = ctrl.Antecedent(np.arange(10,31,1),'tip')

food['poor'] = fuzz.trimf(food.universe,[0,0,5])
food['average'] = fuzz.trimf(food.universe,[0,5,10])
food['good'] = fuzz.trimf(food.universe,[5,10,10])
service['poor'] = fuzz.trimf(service.universe,[0,0,5])
service['average'] = fuzz.trimf(service.universe,[0,5,10])
service['good'] = fuzz.trimf(service.universe,[5,10,10])
tip['less'] = fuzz.trimf(tip.universe,[10,10,20])
tip['normal'] = fuzz.trimf(tip.universe,[10,20,30])
tip['much'] = fuzz.trimf(tip.universe,[20,30,30])

food.view()
service.view()
tip.view()

food['poor'].view()

rule1 = ctrl.Rule(food['poor'] & service['poor'], tip['less'])
rule2 = ctrl.Rule(food['poor'] & service['average'], tip['less'])
rule3 = ctrl.Rule(food['poor'] & service['good'], tip['normal'])
rule4 = ctrl.Rule(food['average'] & service['poor'], tip['normal'])
rule5 = ctrl.Rule(food['average'] & service['average'], tip['normal'])
rule6 = ctrl.Rule(food['average'] & service['good'], tip['much'])
rule7 = ctrl.Rule(food['good'] & service['poor'], tip['normal'])
rule8 = ctrl.Rule(food['good'] & service['average'], tip['much'])
rule9 = ctrl.Rule(food['good'] & service['good'], tip['much'])

tipping_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9])
tipping =ctrl.ControlSystemSimulation(tipping_ctrl)
tipping.input['food']=  6.1
tipping.input['service']= 9.2

tipping.compute()
print(tipping.output['tip'])
tip.view(sim=tipping)

"""Cooking rice

"""

import numpy as np 
import skfuzzy as fuzz 
import matplotlib.pyplot as plt 
from skfuzzy import control as ctrl

rice = ctrl.Antecedent(np.arange(0,180,1),'food')
time = ctrl.Antecedent(np.arange(2,2000,1),'service')
power = ctrl.Antecedent(np.arange(0,100,1),'tip')

rice['rit'] = fuzz.trimf(rice.universe,[200,200,])
rice['it'] = fuzz.trimf(rice.universe,[0,5,10])
rice['tb'] = fuzz.trimf(rice.universe,[5,10,10])
rice['n'] = fuzz.trimf(rice.universe,[0,0,5])
rice['rn'] = fuzz.trimf(rice.universe,[0,5,10])