# -*- coding: utf-8 -*-
"""CookingRice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DAYVnaDTOQVu5vYGufnyGhUI8qRjb2Bc
"""

# code thoi gian nau gao
import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt
from skfuzzy import control as ctrl

rice=ctrl.Antecedent(np.arange(0.2,2,0.2),'Rice')
time=ctrl.Antecedent(np.arange(10,180,10),'Time')
power=ctrl.Consequent(np.arange(0,100,1),'Power')

time['vs']=fuzz.trimf(time.universe,[0,10,20])
time['s']=fuzz.trimf(time.universe,[20,30,40])
time['av']=fuzz.trimf(time.universe,[40,60,90])
time['f']=fuzz.trimf(time.universe,[90,120,150])
time['vf']=fuzz.trimf(time.universe,[150,180,180])

rice['vm']=fuzz.trimf(rice.universe,[0,0.2,0.3])
rice['m']=fuzz.trimf(rice.universe,[0.3,0.5,0.8])
rice['av']=fuzz.trimf(rice.universe,[0.8,1,1.2])
rice['l']=fuzz.trimf(rice.universe,[1.2,1.5,1.7])
rice['f']=fuzz.trimf(rice.universe,[1.7,2,2])

power['1']=fuzz.trimf(power.universe,[0,45,50])
power['2']=fuzz.trimf(power.universe,[50,60,65])
power['3']=fuzz.trimf(power.universe,[65,75,78])
power['4']=fuzz.trimf(power.universe,[78,85,88])
power['5']=fuzz.trimf(power.universe,[88,95,100])

rale1=ctrl.Rule(time['vs'] & rice['vm'],power['2'])
rale2=ctrl.Rule(time['vs'] & rice['m'],power['3'])
rale3=ctrl.Rule(time['vs'] & rice['av'],power['4'])
rale4=ctrl.Rule(time['vs'] & rice['l'],power['5'])
rale5=ctrl.Rule(time['vs'] & rice['f'],power['5'])
rale6=ctrl.Rule(time['s'] & rice['vm'],power['2'])
rale7=ctrl.Rule(time['s'] & rice['m'],power['3'])
rale8=ctrl.Rule(time['s'] & rice['av'],power['3'])
rale9=ctrl.Rule(time['s'] & rice['l'],power['5'])
rale10=ctrl.Rule(time['s'] & rice['f'],power['5'])
rale11=ctrl.Rule(time['av'] & rice['vm'],power['1'])
rale12=ctrl.Rule(time['av'] & rice['m'],power['2'])
rale13=ctrl.Rule(time['av'] & rice['av'],power['3'])
rale14=ctrl.Rule(time['av'] & rice['l'],power['4'])
rale15=ctrl.Rule(time['av'] & rice['f'],power['4'])
rale16=ctrl.Rule(time['f'] & rice['vm'],power['1'])
rale17=ctrl.Rule(time['f'] & rice['m'],power['2'])
rale18=ctrl.Rule(time['f'] & rice['av'],power['2'])
rale19=ctrl.Rule(time['f'] & rice['l'],power['4'])
rale20=ctrl.Rule(time['f'] & rice['f'],power['4'])
rale21=ctrl.Rule(time['vf'] & rice['vm'],power['1'])
rale22=ctrl.Rule(time['vf'] & rice['m'],power['2'])
rale23=ctrl.Rule(time['vf'] & rice['av'],power['2'])
rale24=ctrl.Rule(time['vf'] & rice['l'],power['3'])
rale25=ctrl.Rule(time['vf'] & rice['f'],power['3'])

powering_ctrl= ctrl.ControlSystem([rale1,rale2,rale3,rale4,rale5,rale6,rale7,rale8,rale9,rale10,rale11,rale12,rale13,rale14,rale15,rale16,rale17,rale18,rale19,rale20,rale21,rale22,rale23,rale24,rale25])
powering= ctrl.ControlSystemSimulation(powering_ctrl)
powering.input['Rice']=0.5
powering.input['Time']= 30
powering.compute()
print(powering.output['Power'])

power.view(sim=powering)